export const HEROES = {
  tan: {
    id: 'tan',
    name: 'Tan',
    baseHP: 120,
    normalAttack: {
      name: 'Palo-Palo Lang',
      description: 'Low damage na pang-asar. Walang cooldown.',
      type: 'damage',
      effect: {
        kind: 'damage',
        amount: 12,
        target: 'enemy',
      },
    },
    skills: [
      {
        name: 'Ayy Inday!',
        description: 'Sabay palo, sabay arte: medium damage + small heal sa sarili.',
        type: 'damage',
        cooldown: 2,
        effect: {
          kind: 'damage_and_heal',
          damage: 24,
          healSelf: 10,
          target: 'enemy',
          notes: 'Sabay palo, sabay arte.',
        },
      },
      {
        name: 'Tsismis Barrage',
        description: 'Low damage + enemy attack -20% for 2 turns.',
        type: 'utility',
        cooldown: 2,
        effect: {
          kind: 'damage_and_attack_down',
          damage: 16,
          attackDownPct: 0.2,
          turns: 2,
          target: 'enemy',
          notes: 'Napahina dahil sa chismis.',
        },
      },
      {
        name: 'Laban Kung Laban',
        description: 'Gain shield (defense boost). No damage.',
        type: 'defense',
        cooldown: 2,
        effect: {
          kind: 'shield',
          shield: 26,
          turns: 2,
          target: 'self',
          notes: 'Defense skill; does not deal damage.',
        },
      },
      {
        name: 'Inday Rage Mode',
        description: '+Attack +Speed for 2 turns. Power mode ni Inday.',
        type: 'ultimate',
        cooldown: 4,
        effect: {
          kind: 'buff_attack_and_speed',
          attackUpPct: 0.25,
          speedUpPct: 0.25,
          turns: 2,
          target: 'self',
          notes: 'Power mode ni Inday.',
        },
      },
    ],
  },

  damara: {
    id: 'damara',
    name: 'Damara',
    baseHP: 140,
    normalAttack: {
      name: 'Suntok na Makunat',
      description: 'Low damage na matigas ang dating. Walang cooldown.',
      type: 'damage',
      effect: {
        kind: 'damage',
        amount: 10,
        target: 'enemy',
      },
    },
    skills: [
      {
        name: 'Balat na Makapal',
        description: 'Reduce incoming damage by 50% for 1 turn.',
        type: 'defense',
        cooldown: 2,
        effect: {
          kind: 'damage_reduction',
          reduction: 0.5,
          turns: 1,
          target: 'self',
          notes: 'Defense skill; does not deal damage.',
        },
      },
      {
        name: 'Pisngi Slam',
        description: 'Medium damage + stun (1 turn).',
        type: 'damage',
        cooldown: 5,
        effect: {
          kind: 'damage_and_stun',
          damage: 22,
          stunTurns: 1,
          target: 'enemy',
        },
      },
      {
        name: 'Self Love Muna',
        description: 'Heal big HP.',
        type: 'defense',
        cooldown: 3,
        effect: {
          kind: 'heal',
          amount: 24,
          target: 'self',
          notes: 'Defense/sustain; does not deal damage.',
        },
      },
      {
        name: 'Hindi Ako Tinatablan',
        description: 'Immune to damage for 1 turn. Panic button.',
        type: 'ultimate',
        cooldown: 4,
        effect: {
          kind: 'immunity',
          turns: 1,
          target: 'self',
          notes: 'Ultimate defense; blocks damage for 1 turn.',
        },
      },
    ],
  },

  azel: {
    id: 'azel',
    name: 'Azel',
    baseHP: 120,
    normalAttack: {
      name: 'Singit Hit',
      description: 'Low damage na mabilis. Walang cooldown.',
      type: 'damage',
      effect: {
        kind: 'damage',
        amount: 11,
        target: 'enemy',
      },
    },
    skills: [
      {
        name: 'Banlag Strike',
        description: 'High damage but 20% chance to miss.',
        type: 'damage',
        cooldown: 2,
        effect: {
          kind: 'damage_with_miss',
          damage: 34,
          missChance: 0.15,
          target: 'enemy',
          notes: 'High risk, high reward.',
        },
      },
      {
        name: 'Liko Liko',
        description: 'Dodge next attack.',
        type: 'defense',
        cooldown: 2,
        effect: {
          kind: 'evasion',
          chance: 1,
          turns: 1,
          target: 'self',
          notes: 'Guaranteed dodge for the next incoming hit within 1 turn.',
        },
      },
      {
        name: 'Gulat Ka No?',
        description: 'Medium damage + enemy cooldown +2.',
        type: 'utility',
        cooldown: 2,
        effect: {
          kind: 'damage_and_cooldown_increase',
          damage: 20,
          increaseEnemyCooldownBy: 2,
          target: 'enemy',
          notes: 'Adds +2 to all enemy cooldown counters.',
        },
      },
      {
        name: 'Walang Makaka-Tama',
        description: 'Dodge all attacks for 1 turn + counter damage.',
        type: 'ultimate',
        cooldown: 4,
        effect: {
          kind: 'dodge_all_and_counter',
          dodgeAllTurns: 1,
          counterDamage: 20,
          counterTurns: 1,
          target: 'self',
          notes: 'Defensive ultimate; counters when hit.',
        },
      },
    ],
  },

  ruis: {
    id: 'ruis',
    name: 'Ruis',
    baseHP: 130,
    normalAttack: {
      name: 'Trip Lang',
      description: 'Low damage. Walang cooldown. Pang-asar lang.',
      type: 'damage',
      effect: {
        kind: 'damage',
        amount: 12,
        target: 'enemy',
      },
    },
    skills: [
      {
        name: 'Ay Beh!',
        description: 'Medium damage + random effect: stun, heal self, extra damage, OR recoil.',
        type: 'damage',
        cooldown: 2,
        effect: {
          kind: 'damage_and_random',
          damage: 22,
          table: [
            { kind: 'stun', turns: 1 },
            { kind: 'heal_self', amount: 14 },
            { kind: 'bonus_damage', amount: 12 },
            { kind: 'self_damage', amount: 8 },
          ],
          target: 'enemy',
          notes: 'Chaotic RNG effect table.',
        },
      },
      {
        name: 'Drama Mode',
        description: 'Enemy attack reduced + you gain small heal.',
        type: 'utility',
        cooldown: 3,
        effect: {
          kind: 'attack_down_and_heal',
          attackDownPct: 0.2,
          healSelf: 10,
          turns: 2,
          target: 'enemy',
          notes: 'Debuff + sustain.',
        },
      },
      {
        name: 'Biglang Bawi',
        description: 'Reflect 50% damage this turn.',
        type: 'utility',
        cooldown: 3,
        effect: {
          kind: 'reflect',
          reflectPct: 0.5,
          turns: 1,
          target: 'self',
          notes: 'Reflects incoming damage for the current turn window.',
        },
      },
      {
        name: 'Finale Performance',
        description: 'Huge damage but self takes small recoil.',
        type: 'ultimate',
        cooldown: 4,
        effect: {
          kind: 'damage_with_recoil',
          damage: 42,
          recoilSelf: 10,
          target: 'enemy',
          notes: 'Big burst with recoil.',
        },
      },
    ],
  },

  chano: {
    id: 'chano',
    name: 'Chano',
    baseHP: 105,
    normalAttack: {
      name: 'Tamad na Suntok',
      description: 'Walang gana pero nakakasakit pa rin. Walang cooldown.',
      type: 'damage',
      effect: {
        kind: 'damage',
        amount: 9,
        target: 'enemy',
      },
    },
    skills: [
      {
        name: 'Bahala Na, Basta Makatulog',
        description: 'Bulag na swing — pag natama, masakit. Pag hindi, tulog ulit.',
        type: 'damage',
        cooldown: 2,
        effect: {
          kind: 'damage_with_miss',
          damage: 32,
          missChance: 0.35,
          target: 'enemy',
          notes: 'High risk — harder miss chance than Azel. Lazy glass cannon.',
        },
      },
      {
        name: 'Gym Tomorrow Na Lang',
        description: 'Too lazy to fight back. Kapag tinamaan ka — your problem.',
        type: 'defense',
        cooldown: 3,
        effect: {
          kind: 'reflect',
          reflectPct: 0.4,
          turns: 2,
          target: 'self',
          notes: 'Reflects 40% of incoming damage for 2 turns. Passive staller.',
        },
      },
      {
        name: 'Sige, Isang Bigay Pa!',
        description: 'Last rep energy. Hits hard pero sumasakit sa sarili.',
        type: 'damage',
        cooldown: 3,
        effect: {
          kind: 'damage_with_recoil',
          damage: 42,
          recoilSelf: 18,
          target: 'enemy',
          notes: 'Highest base skill damage — but takes heavy recoil. Very risky pre-Turn 8.',
        },
      },
      {
        name: 'Tara GYM!',
        description: 'Nag-gym na si Chano. Heal + attack boost + stun chance + armor — lahat. God mode.',
        type: 'ultimate',
        cooldown: 6,
        minTurn: 12,
        effect: {
          kind: 'gym_mode',
          healPct: 0.5,
          attackUpPct: 0.5,
          stunChancePct: 0.25,
          armorPct: 0.25,
          turns: 3,
          target: 'self',
          notes: 'Cannot be used before Turn 12. Heals 50% max HP, +50% atk, +25% stun on hit, +25% damage reduction for 3 turns.',
        },
      },
    ],
  },
}

export const GLOBAL_ITEMS = [
  {
    id: 'tsinelas_ni_nanay',
    name: 'Tsinelas ni Nanay',
    description: '+Attack (passive).',
    effect: { kind: 'attack_up', attackUpPct: 0.1, mode: 'passive', notes: 'Increases all damage dealt by 10%.' },
  },
  {
    id: 'anting_anting',
    name: 'Anting-Anting',
    description: '+Defense (passive).',
    effect: {
      kind: 'defense_up',
      damageReductionPct: 0.1,
      mode: 'passive',
      notes: 'Reduces damage taken by 10% (after skill reductions).',
    },
  },
  {
    id: 'lucky_3_coins',
    name: 'Lucky 3 Coins',
    description: '+Crit chance (passive).',
    effect: {
      kind: 'crit_chance',
      critChance: 0.15,
      critDamagePct: 0.35,
      mode: 'passive',
      notes: '15% chance to deal +35% damage.',
    },
  },
  {
    id: 'fishball_power',
    name: 'Fishball Power',
    description: 'Heal every turn (small).',
    effect: {
      kind: 'heal_per_turn',
      healPerTurn: 5,
      when: 'turn_start',
      mode: 'passive',
      notes: 'Heals 5 HP at the start of your turn.',
    },
  },
  {
    id: 'energy_drink',
    name: 'Energy Drink',
    description: '+Speed (cooldown momentum).',
    effect: {
      kind: 'speed_up',
      reduceRandomCooldownBy: 1,
      when: 'turn_start',
      mode: 'passive',
      notes: 'At turn start, reduces 1 random skill cooldown by 1 (if any are on cooldown).',
    },
  },
  {
    id: 'jacket_ni_kuya',
    name: 'Jacket ni Kuya',
    description: 'Reduce damage taken (flat).',
    effect: {
      kind: 'flat_damage_reduction',
      reduceBy: 6,
      mode: 'passive',
      notes: 'Reduces incoming damage by 6 (after percentage reductions).',
    },
  },
  {
    id: 'old_nokia',
    name: 'Old Nokia',
    description: 'Chance to stun enemy on hit.',
    effect: {
      kind: 'stun_chance_on_damage',
      chance: 0.15,
      stunTurns: 1,
      mode: 'triggered',
      notes: 'On dealing damage, 15% chance to stun the target for 1 turn.',
    },
  },
  {
    id: 'chismis_notebook',
    name: 'Chismis Notebook',
    description: 'Increase debuff & DOT effects.',
    effect: {
      kind: 'debuff_boost',
      debuffMultiplier: 1.25,
      mode: 'passive',
      notes: 'Your debuffs and DOTs are 25% stronger (e.g., attack down, damage over time).',
    },
  },
  {
    id: 'pamahiin_charm',
    name: 'Pamahiin Charm',
    description: 'Random small buffs each turn.',
    effect: {
      kind: 'random_buff_each_turn',
      when: 'turn_start',
      mode: 'passive',
      notes: 'Each turn start grants a small random buff (heal/attack/defense/evasion).',
    },
  },
  {
    id: 'final_blessing',
    name: 'Final Blessing',
    description: 'Boost ultimate skill damage.',
    effect: {
      kind: 'ultimate_damage_boost',
      bonusDamagePct: 0.15,
      mode: 'passive',
      notes: 'Ultimates deal +15% damage.',
    },
  }
]
